"""master migration

Revision ID: 10d865c534e7
Revises: 
Create Date: 2026-01-04 10:22:16.119658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d865c534e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_campaign_slug'), ['slug'])

    with op.batch_alter_table('industry', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_industry_slug'), ['slug'])

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_page_slug'), ['slug'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_api_key'), ['api_key'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_uid'), ['uid'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_uid'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_api_key'), type_='unique')
        batch_op.drop_column('api_key')

    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_page_slug'), type_='unique')

    with op.batch_alter_table('industry', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_industry_slug'), type_='unique')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_campaign_slug'), type_='unique')

    # ### end Alembic commands ###
